'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4927
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_blue16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_blue16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_000_medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_000_medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_180_medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_180_medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property black() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("black", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_stop_square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_stop_square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cross_circle16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_circle16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cross16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dll16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dllIcon16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dllIcon16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_text_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_text_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exe16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exe16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exe32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exe32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property file_info32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_info32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property globe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("handle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hideDetails() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hideDetails", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ie716() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ie716", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ie732() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ie732", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information_frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property locked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnify32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnify32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitoring32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitoring32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property network16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property network32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open_folder32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_folder32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property options16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("options16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property options32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("options32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_info32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_info32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypal_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property process() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("process", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property process32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("process32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scripting16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scripting16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shield16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shield32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sourceforge_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sourceforge_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speed32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_type32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start_type32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property target16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("target16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property target32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("target32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property taskmgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskmgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 0	Reserved
        '''1	TCP Port Service Multiplexer
        '''2	Management Utility
        '''3	Compression Process
        '''5	Remote Job Entry
        '''7	Echo
        '''9	Discard
        '''11	Active Users
        '''13	DAYTIME - (RFC 867)
        '''17	Quote of the Day
        '''18	Message Send Protocol
        '''19	Character Generator
        '''20	FTP - data
        '''21	FTP-control (command)
        '''22	Secure Shell (SSH)-used for secure logins, file transfers (scp, sftp) and port forwarding
        '''23	Telnet protocol-unencrypted text communications
        '''25	Simple Mail Transfer Protocol (SMTP)-used for e-mail routing between mail servers        ''' [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property tcp() As String
            Get
                Return ResourceManager.GetString("tcp", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property thread() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thread", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trash32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 0	Reserved
        '''1	TCP Port Service Multiplexer
        '''2	Management Utility
        '''3	Compression Process
        '''5	Remote Job Entry
        '''7	Echo
        '''9	Discard
        '''11	Active Users
        '''13	DAYTIME - (RFC 867)
        '''17	Quote of the Day
        '''18	Message Send Protocol
        '''19	Character Generator
        '''22	Secure Shell (SSH)-used for secure logins, file transfers (scp, sftp) and port forwarding
        '''35	Any private printer server protocol
        '''35	QMS Magicolor 2 printer server protocol
        '''37	TIME protocol
        '''39	Resource Location Protocol (RLP)-used for determining the location of hig [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property udp() As String
            Get
                Return ResourceManager.GetString("udp", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property unlock32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unlock32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window_add32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_add32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yapm32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yapm32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
