'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4016
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property ProcessInterval() As Integer
            Get
                Return CType(Me("ProcessInterval"),Integer)
            End Get
            Set
                Me("ProcessInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2500")>  _
        Public Property ServiceInterval() As Integer
            Get
                Return CType(Me("ServiceInterval"),Integer)
            End Get
            Set
                Me("ServiceInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property SystemInterval() As Integer
            Get
                Return CType(Me("SystemInterval"),Integer)
            End Get
            Set
                Me("SystemInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property TrayInterval() As Integer
            Get
                Return CType(Me("TrayInterval"),Integer)
            End Get
            Set
                Me("TrayInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("102400")>  _
        Public Property HistorySize() As Integer
            Get
                Return CType(Me("HistorySize"),Integer)
            End Get
            Set
                Me("HistorySize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WindowsStartup() As Boolean
            Get
                Return CType(Me("WindowsStartup"),Boolean)
            End Get
            Set
                Me("WindowsStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartHidden() As Boolean
            Get
                Return CType(Me("StartHidden"),Boolean)
            End Get
            Set
                Me("StartHidden") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("English")>  _
        Public Property Lang() As String
            Get
                Return CType(Me("Lang"),String)
            End Get
            Set
                Me("Lang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TopMost() As Boolean
            Get
                Return CType(Me("TopMost"),Boolean)
            End Get
            Set
                Me("TopMost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstTime() As Boolean
            Get
                Return CType(Me("FirstTime"),Boolean)
            End Get
            Set
                Me("FirstTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstTimeSBA() As Boolean
            Get
                Return CType(Me("FirstTimeSBA"),Boolean)
            End Get
            Set
                Me("FirstTimeSBA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseRibbonStyle() As Boolean
            Get
                Return CType(Me("UseRibbonStyle"),Boolean)
            End Get
            Set
                Me("UseRibbonStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-8323328")>  _
        Public Property NewItemColor() As Integer
            Get
                Return CType(Me("NewItemColor"),Integer)
            End Get
            Set
                Me("NewItemColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-49104")>  _
        Public Property DeletedItemColor() As Integer
            Get
                Return CType(Me("DeletedItemColor"),Integer)
            End Get
            Set
                Me("DeletedItemColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CloseYAPMWithCloseButton() As Boolean
            Get
                Return CType(Me("CloseYAPMWithCloseButton"),Boolean)
            End Get
            Set
                Me("CloseYAPMWithCloseButton") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowTrayIcon() As Boolean
            Get
                Return CType(Me("ShowTrayIcon"),Boolean)
            End Get
            Set
                Me("ShowTrayIcon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Priority() As Integer
            Get
                Return CType(Me("Priority"),Integer)
            End Get
            Set
                Me("Priority") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property TaskInterval() As Integer
            Get
                Return CType(Me("TaskInterval"),Integer)
            End Get
            Set
                Me("TaskInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property NetworkInterval() As Integer
            Get
                Return CType(Me("NetworkInterval"),Integer)
            End Get
            Set
                Me("NetworkInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.google.com/search?hl=en&q=ITEM")>  _
        Public Property SearchEngine() As String
            Get
                Return CType(Me("SearchEngine"),String)
            End Get
            Set
                Me("SearchEngine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarnDangerousActions() As Boolean
            Get
                Return CType(Me("WarnDangerousActions"),Boolean)
            End Get
            Set
                Me("WarnDangerousActions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HideWhenMinimized() As Boolean
            Get
                Return CType(Me("HideWhenMinimized"),Boolean)
            End Get
            Set
                Me("HideWhenMinimized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HideWhenClosed() As Boolean
            Get
                Return CType(Me("HideWhenClosed"),Boolean)
            End Get
            Set
                Me("HideWhenClosed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ReplaceTaskmgr() As Boolean
            Get
                Return CType(Me("ReplaceTaskmgr"),Boolean)
            End Get
            Set
                Me("ReplaceTaskmgr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Processes")>  _
        Public Property SelectedTab() As String
            Get
                Return CType(Me("SelectedTab"),String)
            End Get
            Set
                Me("SelectedTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?540$CpuUsage?73$Process?233$")>  _
        Public Property COLmain_task() As String
            Get
                Return CType(Me("COLmain_task"),String)
            End Get
            Set
                Me("COLmain_task") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?106$PID?50$UserName?124$ParentName?94$CpuUsage?68$AverageCpuUsage?61$TotalCp"& _ 
            "uTime?90$HandleCount?56$ThreadCount?50$WorkingSet?76$Priority?90$Path?420$")>  _
        Public Property COLmain_process() As String
            Get
                Return CType(Me("COLmain_process"),String)
            End Get
            Set
                Me("COLmain_process") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?107$Version?113$Description?279$CompanyName?138$Path?330$ProcessId?60$")>  _
        Public Property COLmain_module() As String
            Get
                Return CType(Me("COLmain_module"),String)
            End Get
            Set
                Me("COLmain_module") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Id?60$Priority?88$State?74$WaitReason?98$CreateTime?173$TotalTime?90$StartAddress"& _ 
            "?83$AffinityMask?78$ContextSwitchCount?118$ContextSwitchDelta?114$ProcessId?68$")>  _
        Public Property COLmain_thread() As String
            Get
                Return CType(Me("COLmain_thread"),String)
            End Get
            Set
                Me("COLmain_thread") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Type?113$Name?400$HandleCount?70$PointerCount?70$ObjectCount?70$Handle?60$Process"& _ 
            "?51$")>  _
        Public Property COLmain_handle() As String
            Get
                Return CType(Me("COLmain_handle"),String)
            End Get
            Set
                Me("COLmain_handle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Id?84$Caption?368$Process?162$IsTask?49$Enabled?56$Visible?47$ThreadId?61$")>  _
        Public Property COLmain_window() As String
            Get
                Return CType(Me("COLmain_window"),String)
            End Get
            Set
                Me("COLmain_window") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?112$DisplayName?144$State?77$StartType?86$ImagePath?230$ServiceType?113$Proc"& _ 
            "ess?127$")>  _
        Public Property COLmain_service() As String
            Get
                Return CType(Me("COLmain_service"),String)
            End Get
            Set
                Me("COLmain_service") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Local?328$Remote?271$Protocol?65$State?150$")>  _
        Public Property COLmain_network() As String
            Get
                Return CType(Me("COLmain_network"),String)
            End Get
            Set
                Me("COLmain_network") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?177$Status?100$Description?327$")>  _
        Public Property COLprocdetail_privilege() As String
            Get
                Return CType(Me("COLprocdetail_privilege"),String)
            End Get
            Set
                Me("COLprocdetail_privilege") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?173$Protection?66$Address?90$Size?66$File?223$")>  _
        Public Property COLprocdetail_memory() As String
            Get
                Return CType(Me("COLprocdetail_memory"),String)
            End Get
            Set
                Me("COLprocdetail_memory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?121$DisplayName?243$State?79$StartType?70$ImagePath?250$ServiceType?100$")>  _
        Public Property COLprocdetail_service() As String
            Get
                Return CType(Me("COLprocdetail_service"),String)
            End Get
            Set
                Me("COLprocdetail_service") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Local?238$Remote?223$Protocol?60$State?113$")>  _
        Public Property COLprocdetail_network() As String
            Get
                Return CType(Me("COLprocdetail_network"),String)
            End Get
            Set
                Me("COLprocdetail_network") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Type?95$Name?400$HandleCount?70$PointerCount?69$ObjectCount?66$Handle?52$")>  _
        Public Property COLprocdetail_handle() As String
            Get
                Return CType(Me("COLprocdetail_handle"),String)
            End Get
            Set
                Me("COLprocdetail_handle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Id?96$Caption?325$IsTask?44$Enabled?64$Visible?51$ThreadId?63$")>  _
        Public Property COLprocdetail_window() As String
            Get
                Return CType(Me("COLprocdetail_window"),String)
            End Get
            Set
                Me("COLprocdetail_window") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Id?60$ContextSwitchDelta?118$Priority?100$State?70$WaitReason?100$CreateTime?119$"& _ 
            "TotalTime?200$StartAddress?100$ContextSwitchCount?200$")>  _
        Public Property COLprocdetail_thread() As String
            Get
                Return CType(Me("COLprocdetail_thread"),String)
            End Get
            Set
                Me("COLprocdetail_thread") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Name?90$Version?85$Description?210$CompanyName?150$Path?300$Address?80$")>  _
        Public Property COLprocdetail_module() As String
            Get
                Return CType(Me("COLprocdetail_module"),String)
            End Get
            Set
                Me("COLprocdetail_module") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Variable?176$Value?445$")>  _
        Public Property COLprocdetail_envvariable() As String
            Get
                Return CType(Me("COLprocdetail_envvariable"),String)
            End Get
            Set
                Me("COLprocdetail_envvariable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("General")>  _
        Public Property ProcSelectedTab() As String
            Get
                Return CType(Me("ProcSelectedTab"),String)
            End Get
            Set
                Me("ProcSelectedTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("General - 1")>  _
        Public Property ServSelectedTab() As String
            Get
                Return CType(Me("ServSelectedTab"),String)
            End Get
            Set
                Me("ServSelectedTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Date & Time?164$Type?102$Description?343$")>  _
        Public Property COLprocdetail_log() As String
            Get
                Return CType(Me("COLprocdetail_log"),String)
            End Get
            Set
                Me("COLprocdetail_log") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutomaticInternetInfos() As Boolean
            Get
                Return CType(Me("AutomaticInternetInfos"),Boolean)
            End Get
            Set
                Me("AutomaticInternetInfos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShouldUpgrade() As Boolean
            Get
                Return CType(Me("ShouldUpgrade"),Boolean)
            End Get
            Set
                Me("ShouldUpgrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingBeingDebugged() As Boolean
            Get
                Return CType(Me("EnableHighlightingBeingDebugged"),Boolean)
            End Get
            Set
                Me("EnableHighlightingBeingDebugged") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingElevated() As Boolean
            Get
                Return CType(Me("EnableHighlightingElevated"),Boolean)
            End Get
            Set
                Me("EnableHighlightingElevated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingJobProcess() As Boolean
            Get
                Return CType(Me("EnableHighlightingJobProcess"),Boolean)
            End Get
            Set
                Me("EnableHighlightingJobProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingOwnedProcess() As Boolean
            Get
                Return CType(Me("EnableHighlightingOwnedProcess"),Boolean)
            End Get
            Set
                Me("EnableHighlightingOwnedProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingServiceProcess() As Boolean
            Get
                Return CType(Me("EnableHighlightingServiceProcess"),Boolean)
            End Get
            Set
                Me("EnableHighlightingServiceProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingSystemProcess() As Boolean
            Get
                Return CType(Me("EnableHighlightingSystemProcess"),Boolean)
            End Get
            Set
                Me("EnableHighlightingSystemProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingCriticalProcess() As Boolean
            Get
                Return CType(Me("EnableHighlightingCriticalProcess"),Boolean)
            End Get
            Set
                Me("EnableHighlightingCriticalProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableHighlightingSuspendedThread() As Boolean
            Get
                Return CType(Me("EnableHighlightingSuspendedThread"),Boolean)
            End Get
            Set
                Me("EnableHighlightingSuspendedThread") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 192, 255")>  _
        Public Property HighlightingColorBeingDebugged() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorBeingDebugged"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorBeingDebugged") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192, 255, 192")>  _
        Public Property HighlightingColorJobProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorJobProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorJobProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 192")>  _
        Public Property HighlightingColorOwnedProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorOwnedProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorOwnedProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192, 255, 255")>  _
        Public Property HighlightingColorServiceProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorServiceProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorServiceProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192, 192, 255")>  _
        Public Property HighlightingColorSystemProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorSystemProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorSystemProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 128, 0")>  _
        Public Property HighlightingColorCriticalProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorCriticalProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorCriticalProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 192")>  _
        Public Property HighlightingColorSuspendedThread() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorSuspendedThread"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorSuspendedThread") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 192, 128")>  _
        Public Property HighlightingColorElevatedProcess() As Global.System.Drawing.Color
            Get
                Return CType(Me("HighlightingColorElevatedProcess"),Global.System.Drawing.Color)
            End Get
            Set
                Me("HighlightingColorElevatedProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property HighlightingPriorityBeingDebugged() As Byte
            Get
                Return CType(Me("HighlightingPriorityBeingDebugged"),Byte)
            End Get
            Set
                Me("HighlightingPriorityBeingDebugged") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property HighlightingPriorityJobProcess() As Byte
            Get
                Return CType(Me("HighlightingPriorityJobProcess"),Byte)
            End Get
            Set
                Me("HighlightingPriorityJobProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property HighlightingPriorityOwnedProcess() As Byte
            Get
                Return CType(Me("HighlightingPriorityOwnedProcess"),Byte)
            End Get
            Set
                Me("HighlightingPriorityOwnedProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property HighlightingPriorityServiceProcess() As Byte
            Get
                Return CType(Me("HighlightingPriorityServiceProcess"),Byte)
            End Get
            Set
                Me("HighlightingPriorityServiceProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property HighlightingPrioritySystemProcess() As Byte
            Get
                Return CType(Me("HighlightingPrioritySystemProcess"),Byte)
            End Get
            Set
                Me("HighlightingPrioritySystemProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property HighlightingPriorityCriticalProcess() As Byte
            Get
                Return CType(Me("HighlightingPriorityCriticalProcess"),Byte)
            End Get
            Set
                Me("HighlightingPriorityCriticalProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property HighlightingPriorityElevatedProcess() As Byte
            Get
                Return CType(Me("HighlightingPriorityElevatedProcess"),Byte)
            End Get
            Set
                Me("HighlightingPriorityElevatedProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property HighlightingPrioritySuspendedThread() As Byte
            Get
                Return CType(Me("HighlightingPrioritySuspendedThread"),Byte)
            End Get
            Set
                Me("HighlightingPrioritySuspendedThread") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowUserGroupDomain() As Boolean
            Get
                Return CType(Me("ShowUserGroupDomain"),Boolean)
            End Get
            Set
                Me("ShowUserGroupDomain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8081")>  _
        Public Property RemotePort() As Integer
            Get
                Return CType(Me("RemotePort"),Integer)
            End Get
            Set
                Me("RemotePort") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.YAPM.My.MySettings
            Get
                Return Global.YAPM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
